version: '3.1'
services:
  mysql:
    container_name: mysql
    image: mysql:8.3.0
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test:  mysql sys --user=root --password='r00t' --silent --execute "SELECT 1;"
      interval: 10s
      timeout: 20s
      retries: 10
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: r00t
    ports:
      - 3306:3306
    networks:
      - backup-team

networks:
  backup-team:
